language: ruby

script: bundle exec rake ci

notifications:
  email: false

matrix:
  include:
    - env: RAILS_VERSION="~> 6.0"
    - env: RAILS_VERSION="~> 5.2"

rvm:
  - 2.7.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: openjdk11
